# This is a basic workflow to help you get started with Actions

name: DEPLOY_ALPACA_BLOG

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Deply To Aliyun OSS
        uses: fangbinwei/aliyun-oss-website-action@v1
        with:
          accessKeyId: ${{ secrets.ALIYUN_ACCESSKEY_ID }}
          accessKeySecret: ${{ secrets.ALIYUN_ACCESSKEY_SECRET }}
          bucket: blog-alpaca-run
          # use your own endpoint
          endpoint: oss-cn-guangzhou.aliyuncs.com
          folder: public
